// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJoLoo32gb2852bADI9YRVxoxGVg_ebxo',
    appId: '1:65990435445:android:fba0579dd7b2b0a63f4e3c',
    messagingSenderId: '65990435445',
    projectId: 'racetrackingapp-e9696',
    storageBucket: 'racetrackingapp-e9696.firebasestorage.app',
  );

}
